### PR TITLE
Clear options

### PR DESCRIPTION
**Pull request by bnmajor**
clear

Relies on #231

### CODE REVIEW

**Comment by cjh1** [comment]
I think rather than adding icon to the plot canvas we should put this in the right click context menu, keeping the canvas clear?

**Comment by bnmajor** [comment]
Sounds good

**Comment by bnmajor** [comment]
@cjh1 Moved the option to the context menu and re-based this branch on master to use the vtk.js revert changes

**Comment by cjh1** [comment]
@bnmajor Changes look good. thank you

**Review by cjh1 — APPROVED** [review]

**Pull request merged**
